export const GET_CUSTOMERS_REQUEST = "GET_CUSTOMERS_REQUEST";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const GET_CUSTOMERS_FAIL = "GET_CUSTOMERS_FAIL";


export const GET_CUSTOMER_DETAILS_REQUEST = "GET_CUSTOMER_DETAILS_REQUEST";
export const GET_CUSTOMER_DETAILS_SUCCESS = "GET_CUSTOMER_DETAILS_SUCCESS";
export const GET_CUSTOMER_DETAILS_FAIL = "GET_CUSTOMER_DETAILS_FAIL";
export const GET_CUSTOMER_DETAILS_RESET = "GET_CUSTOMER_DETAILS_RESET";